import type { TFunction } from "i18next";

/** Flat label map consumed by the print server (English keys as fallbacks there). */
export type ReceiptLabels = Record<string, string>;

export function buildReceiptLabels(t: TFunction): ReceiptLabels {
  return {
    // Bill titles / common
    preSaleBill: t("receipts:preSaleBill"),
    finalBill: t("receipts:finalBill"),
    duplicateFinalBill: t("receipts:duplicateFinalBill"),
    delivery: t("receipts:delivery"),
    bill: t("receipts:bill"),
    thankYou: t("receipts:thankYou"),
    invoice: t("receipts:invoice"),
    table: t("receipts:table"),
    room: t("receipts:room"),
    guest: t("receipts:guest"),
    orderType: t("receipts:orderType"),
    cashier: t("receipts:cashier"),
    customer: t("receipts:customer"),
    phone: t("receipts:phone"),
    address: t("receipts:address"),
    deliveryTime: t("receipts:deliveryTime"),
    item: t("receipts:item"),
    qty: t("receipts:qty"),
    rate: t("receipts:rate"),
    ttl: t("receipts:ttl"),
    items: t("receipts:items"),
    tax: t("receipts:tax"),
    discount: t("receipts:discount"),
    extra: t("receipts:extra"),
    tip: t("receipts:tip"),
    deliveryCharges: t("receipts:deliveryCharges"),
    total: t("receipts:total"),
    payment: t("receipts:payment"),
    change: t("receipts:change"),
    notes: t("receipts:notes"),
    checkClosed: t("receipts:checkClosed"),

    // Refund
    refundReceipt: t("receipts:refundReceipt"),
    originalInvoice: t("receipts:originalInvoice"),
    refundDate: t("receipts:refundDate"),
    refundTotal: t("receipts:refundTotal"),

    // Kitchen / deletion
    kot: t("receipts:kot"),
    newOrder: t("receipts:newOrder"),
    addon: t("receipts:addon"),
    duplicateKot: t("receipts:duplicateKot"),
    deletion: t("receipts:deletion"),
    orderNumber: t("receipts:orderNumber"),
    orderTaker: t("receipts:orderTaker"),
    time: t("receipts:time"),
    reason: t("receipts:reason"),
    note: t("receipts:note"),

    // Summary (reuse summary namespace)
    summaryTitle: t("summary:report.title", { date: "{{date}}" }),
    salesRevenue: t("summary:report.sections.salesRevenue"),
    surchargesTaxes: t("summary:report.sections.surchargesTaxes"),
    settlementCashier: t("summary:report.sections.settlementCashier"),
    operationalControls: t("summary:report.sections.operationalControls"),
    productMix: t("summary:report.sections.productMix"),
    paymentTypes: t("summary:report.sections.paymentTypes"),
    taxesBreakdown: t("summary:report.sections.taxesBreakdown"),
    discountsBreakdown: t("summary:report.sections.discountsBreakdown"),
    extrasBreakdown: t("summary:report.sections.extrasBreakdown"),
    couponsBreakdown: t("summary:report.sections.couponsBreakdown"),
    exclusiveSales: t("summary:report.rows.exclusiveSales"),
    extras: t("summary:report.rows.extras"),
    grossSales: t("summary:report.rows.grossSales"),
    itemDiscounts: t("summary:report.rows.itemDiscounts"),
    subtotalDiscounts: t("summary:report.rows.subtotalDiscounts"),
    couponDiscounts: t("summary:report.rows.couponDiscounts"),
    discountsMinus: t("summary:report.rows.discounts"),
    netSales: t("summary:report.rows.netSales"),
    serviceCharges: t("summary:report.rows.serviceCharges"),
    taxes: t("summary:report.rows.taxes"),
    totalRevenue: t("summary:report.rows.totalRevenue"),
    amountDueBeforeTips: t("summary:report.rows.amountDueBeforeTips"),
    tips: t("summary:report.rows.tips"),
    grandTotalDue: t("summary:report.rows.grandTotalDue"),
    amountCollected: t("summary:report.rows.amountCollected"),
    rounding: t("summary:report.rows.rounding"),
    changeVariance: t("summary:report.rows.changeVariance"),
    voids: t("summary:report.rows.voids"),
    refunds: t("summary:report.rows.refunds"),
    covers: t("summary:report.rows.covers"),
    averageCover: t("summary:report.rows.averageCover"),
    ordersChecks: t("summary:report.rows.ordersChecks"),
    averageOrderCheck: t("summary:report.rows.averageOrderCheck"),
    mixHeaderQtyTotal: `${t("summary:report.columns.qty")}   ${t("summary:report.columns.total")}   %`,
    noCategoryData: t("summary:report.empty.noCategoryData"),
    noPaymentData: t("summary:report.empty.noPaymentData"),
    noTaxRows: t("summary:report.empty.noTaxRows"),
    noDiscountRows: t("summary:report.empty.noDiscountRows"),
    noExtras: t("summary:report.empty.noExtras"),
    noCoupons: t("summary:report.empty.noCoupons"),
  };
}
