export enum Tables {
  categories = 'category',
  outlets = 'outlet',
  closings = 'day_closing',
  customers = 'customer',
  stays = 'stay',
  stay_settlements = 'stay_settlement',
  discounts = 'discount',
  discount_reasons = 'discount_reason',
  role_discount_policies = 'role_discount_policy',
  order_discounts = 'order_discount',
  coupons = 'coupon',
  coupon_redemptions = 'coupon_redemption',
  floors = 'floor',
  tables = 'floor_table',
  kitchens = 'kitchen',
  workflows = 'workflow',
  workflow_stages = 'workflow_stage',
  dishes = 'menu_item',
  modifier_groups = 'modifier_group',
  modifiers = 'modifier',
  dish_modifier_groups = 'menu_item_modifier_group',
  menus = 'menu',
  menu_menu_items = 'menu_menu_item',

  orders = 'order',
  order_extras = 'order_extras',
  order_items = 'order_item',
  order_items_kitchen = 'order_item_kitchen',
  order_meta = 'order_meta',
  order_coupons = 'order_coupon',
  order_payment = 'order_payment',
  order_merge = 'order_merge',
  order_split = 'order_split',
  order_voids = 'order_void',
  order_refunds = 'order_refund',
  order_prints = 'order_print',
  order_taxes = 'order_tax',
  /** Atomic day/global counters for POS invoice_number and auto_id. */
  order_number_seq = 'order_number_seq',

  order_types = 'order_type',
  extras = 'extra',
  payment_types = 'payment_type',
  payment_type_gateway_configs = 'payment_type_gateway_config',
  payment_webhooks = 'payment_webhook',
  printers = 'printer',
  taxes = 'tax',
  users = 'user',
  user_roles = 'user_role',
  shifts = 'shift',
  time_entries = 'time_entry',
  tip_distributions = 'tip_distribution',
  tip_distribution_user_shares = 'tip_distribution_user_share',

  documents = 'document',

  settings = 'setting',
  integration_providers = 'integration_provider',
  integration_provider_configs = 'integration_provider_config',
  integration_installed_providers = 'integration_installed_provider',
  integration_queue = 'integration_queue',
  integration_queue_attempts = 'integration_queue_attempt',
  integration_provider_health = 'integration_provider_health',
  integration_provider_secrets = 'integration_provider_secret',
  integration_provider_certificates = 'integration_provider_certificate',
  integration_provider_webhooks = 'integration_provider_webhook',
  integration_schedules = 'integration_schedule',
  integration_execution_history = 'integration_execution_history',
  integration_order_fiscals = 'integration_order_fiscal',
  integration_entity_mappings = 'integration_entity_mapping',
  integration_oauth_credentials = 'integration_oauth_credential',
  integration_oauth_states = 'integration_oauth_state',
  integration_sync_runs = 'integration_sync_run',
  integration_sync_failures = 'integration_sync_failure',

  auth_permission = 'auth_permission',
  order_edit_requests = 'order_edit_request',
  duos = 'duo',
  tracking = 'tracking',

  accounts = 'account',
  account_groups = 'account_group',
  account_journal_entries = 'account_journal_entry',
  account_journal_lines = 'account_journal_line',
}
